export default {
  filter: "筛选",
  delayTime: "延时",
  Home: {
    charts: "图表",
    scanner: "拍照",
    gallery: "图库",
    jdsearch: "京东搜索",
    skeleton: "骨架屏",
    morandi: "莫兰迪色系",
    draggable: "可拖拽",
    i18: "国际化",
    device: "%{counts} 个设备",
  },
  Button: {
    ok: "确定",
  },
  Route: {
    home: "首页",
    explore: "发现",
    my: "我的",
    settings: "设置",
    systemInfo: "系统信息",
    theme: "换肤",
    profile: "头像&签名",
    baseInfo: "基本信息",
    welcome: "欢迎页",
    changePassword: "修改密码",
    scanner: "扫一扫",
    echartsDemo: "图表示例",
    morandi: "莫兰迪色系",
    draggable: "可拖拽示例",
  },
  MyPage: {
    baseInfo: "基本信息",
    systemIntroduction: "系统特性",
    favorite: "收藏",
    setting: "设置",
    logout: "退出登录",
  },
  BaseInfos: {
    avatar: "头像",
    motto: "签名",
    account: "账号",
    name: "姓名",
    sex: "性别",
    phone: "手机号",
    address: "地址",
  },
  Settings: {
    changePassword: "修改密码",
    systemInfo: "系统信息",
    changeTheme: "更换皮肤",
  },
  ChangePassword: {
    title: "修改密码",
    oldPassword: "原密码",
    oldPasswordPlaceholder: "输入原密码",
    newPassword: "新密码",
    newPasswordPlaceholder: "输入新密码",
    confirmPassword: "确认密码",
    confirmPasswordPlaceholder: "再次输入新密码",
  },
  SystemInfo: {
    appName: "应用名称",
    version: "版本",
    author: "作者",
    email: "邮箱",
    copySuc: "复制邮箱成功，请粘贴使用",
  },
  Theme: {
    classic: "经典",
    green: "墨绿",
    red: "正红",
    blue: "蓝色",
    black: "暗黑",
  },
};
