export default {
  filter: "filters",
  delayTime: "delay time",
  Home: {
    charts: "Charts",
    scanner: "Scanner",
    gallery: "Gallery",
    jdsearch: "JDsearch",
    skeleton: "Skeleton",
    morandi: "Morandi-Colors",
    draggable: "Draggable",
    i18: "i18",
    device: "%{counts} devices",
  },
  Button: {
    ok: "OK",
  },
  Route: {
    home: "Home",
    explore: "Explore",
    my: "My",
    settings: "Settings",
    systemInfo: "System-Info",
    theme: "Theme",
    baseInfo: "Base-Info",
    welcome: "Welcome",
    changePassword: "Change-Password",
    scanner: "Scanner",
    echartsDemo: "Echarts-Demo",
    morandi: "Morandi-Colors",
    draggable: "Draggable-Demo",
  },
  MyPage: {
    baseInfo: "BaseInfo",
    systemIntroduction: "SystemIntroduction",
    favorite: "Favorite",
    setting: "Setting",
    logout: "LogOut",
  },
  BaseInfos: {
    account: "Account",
    name: "Name",
    sex: "Sex",
    phone: "Phone",
    address: "Address",
  },
  Settings: {
    changePassword: "ChangePassword",
    systemInfo: "SystemInfo",
    changeTheme: "ChangeTheme",
  },
  ChangePassword: {
    title: "ChangePassword",
    oldPassword: "OldPassword",
    oldPasswordPlaceholder: "Enter the original password",
    newPassword: "NewPassword",
    newPasswordPlaceholder: "Enter a new password",
    confirmPassword: "ConfirmPassword",
    confirmPasswordPlaceholder: "Confirm the new password",
  },
  SystemInfo: {
    appName: "AppName",
    version: "Version",
    author: "Author",
    email: "Email",
    copySuc: "Copy mailbox successfully, please paste to use",
  },
  Theme: {
    classic: "Classic",
    green: "Green",
    red: "Red",
    blue: "Blue",
    black: "Black",
  },
};
