/**
 * CN I18 config file.
 */
export default {
  filter: "filters",
  delayTime: "delay time",
  exitApp: "Press again to exit",
  Home: {
    charts: "Charts",
    scanner: "Scanner",
    gallery: "Gallery",
    jdsearch: "JDsearch",
    skeleton: "Skeleton",
    morandi: "Morandi-Colors",
    draggable: "Draggable",
    lottie: "Lottie Animation",
    sensors: "sensors",
    i18: "i18",
    device: "%{counts} devices",
    eCharts: {
      chartsDemo: "Echarts-Demo",
      mapDemo: "Map-Demo",
      liquidDemo: "Liquid-Demo",
      extensionDemo: "Extension-Demo",
    },
    search: {
      back: "Back Home",
    },
  },
  Lottie: {
    tips: "Click to play or pause",
  },
  Login: {
    userName: "Type your username",
    password: "Type your password",
    loginButton: "LOGIN",
    loginTips: "Please type your access info!",
    keyboardTitle: "Hey,man! This is ExploreRN!",
    ForgetPassword: "Forget Password?",
    Register: "Register",
    Copyright: "©copyright by supervons MIT,2021",
    CopyrightTitle: "Copyright",
  },
  Register: {
    userName: "Type user name...",
    userEmptyToast: "Please type user name！",
    password: "Password...",
    email: "E-mail Address...",
    emailCode: "E-mail code...",
    send: "Send",
    registerButton: "Register",
  },
  Button: {
    ok: "OK",
    joke: "OK，Cheers!",
  },
  Route: {
    home: "Home",
    explore: "Explore",
    my: "My",
    settings: "Settings",
    systemInfo: "System-Info",
    theme: "Theme",
    profile: "Avatar&Motto",
    baseInfo: "Base-Info",
    welcome: "Welcome",
    changePassword: "Change-Password",
    scanner: "Scanner",
    echartsDemo: "Echarts-Demo",
    morandi: "Morandi-Colors",
    draggable: "Draggable-Demo",
    lottie: "Lottie-Demo",
  },
  Explore: {
    tips: "To be continued...",
  },
  MyPage: {
    baseInfo: "BaseInfo",
    systemIntroduction: "SystemIntroduction",
    favorite: "Favorite",
    setting: "Setting",
    logout: "LogOut",
    logoutTitle: "LOGOUT",
    logoutTips:
      "After logout, you need to type username and password next time.",
    logoutCancel: "CANCEL",
    logoutSure: "OK",
  },
  BaseInfos: {
    avatar: "Avatar",
    motto: "Motto",
    account: "Account",
    name: "Name",
    sex: "Sex",
    phone: "Phone",
    address: "Address",
  },
  Settings: {
    changePassword: "ChangePassword",
    systemInfo: "SystemInfo",
    changeTheme: "ChangeTheme",
  },
  ChangePassword: {
    title: "ChangePassword",
    oldPassword: "OldPassword",
    oldPasswordPlaceholder: "Enter the original password",
    newPassword: "NewPassword",
    newPasswordPlaceholder: "Enter a new password",
    confirmPassword: "ConfirmPassword",
    confirmPasswordPlaceholder: "Confirm the new password",
  },
  SystemInfo: {
    appName: "AppName",
    version: "Version",
    author: "Author",
    email: "Email",
    copySuc: "Copy mailbox successfully, please paste to use",
  },
  SystemIntroduction: {
    introduction_1: "20 + React-Native Components!",
    introduction_2: "All code in github!",
    introduction_3: "Come dance with me!",
  },
  Theme: {
    classic: "Classic",
    green: "Green",
    red: "Red",
    blue: "Blue",
    black: "Black",
  },
};
